backend:
  name: git-gateway
  branch: master
media_folder: public/uploads
public_folder: /uploads
locale: "ja"
collections:
  - name: "class-posts"
    label: "授業"
    folder: "public/collections/class-posts"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "URL"
        name: "slug"
        widget: "string"
      - label: "執筆日"
        name: "published_at"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "記事のタイトル（英語）"
        name: "title"
        widget: "string"
      - label: "記事のタイトル（日本語）"
        name: "title_jp"
        widget: "string"
      - label: "内容"
        name: "body"
        widget: "markdown"
